config/routes.rb
Bookcheck::Application.routes.draw do
  	#get 'sessions/new'

  	#get 'user/new'
  	get "log_out" => "sessions#destroy", :as => "log_out"
	get "log_in" => "sessions#new", :as => "log_in"
	get "sign_up" => "users#new", :as => "sign_up"
	root :to => "users#new"

	resources :users
	resources :sessions

	resources :books do
		resources :comments, :only => :create
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  #attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		#@books = Book.all
		@books = Book.paginate :page => params[:page], :per_page => 10
	end

	def show
		@book = Book.find params[:id]
		@comments = @book.comments
	end

	def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "#{@book.title} saved."
      redirect_to @book
    else
      render :new
    end
  end
  
  def edit
    @book = Book.find params[:id]
  end

  def update
    @book = Book.find params[:id]
    if @book.update_attributes(book_params)
      flash[:notice] = "#{@book.title} saved."
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    book = Book.find params[:id]
    book.destroy
    flash[:notice] = "#{book.title} deleted."
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :thoughts)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		comment = book.comments.new(comment_params)
		comment.save
		flash[:notice] = 'Comment saved!'
		redirect_to book_path(book)
	end
	private
	def comment_params
		params.require(:comment).permit(:author, :text)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
    	session[:user_id] = user.id
    	redirect_to root_url, :notice => "Logged in!"
  	else
    	flash.now.alert = "Invalid email or password"
    	render "new"
  	end
	end

	def destroy
  	session[:user_id] = nil
  	redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
def new
	@user = User.new
end


def create
  	@user = User.new(params[:user])
  	if @user.save
    	redirect_to root_url, :notice => "Signed up!"
  	else
    	render "new"
  	end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
	@user = User.new
end


def create
  	@user = User.new(user_params)
  	if @user.save
    	redirect_to root_url, :notice => "Signed up!"
  	else
    	render "new"
  	end
end
private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/edit.html.erb
<% title "Editing #{@book.title}" %>
 
<%= form_for(@book) do |form| %>
  <p>
    <%= form.label :title %><br/>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :thoughts %><br/>
    <%= form.text_area :thoughts %>
  </p>
 
  <%= form.submit %>
<% end %>

app/views/books/index.html.erb
<% title 'My Books' %>

<% for book in @books do %>
  <h2><%=link_to(h(book.title), book_path(book)) %></h2>
  <p><%= book.thoughts %></p>
<% end %>
<%= will_paginate @books %>
<p>
  Admin actions: <%= link_to 'New Book', new_book_path %>
</p>

app/views/books/new.html.erb
<%= form_for(@book) do |form| %>
  <p>
    <%= form.label :title %><br/>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :thoughts %><br/>
    <%= form.text_area :thoughts %>
  </p>
 
  <%= form.submit %>
<% end %>

app/views/books/show.html.erb
<% title @book.title %>
 
<h2><%=link_to(h(@book.title), book_path(@book)) %></h2>
<p><%= @book.thoughts %></p>

<% if @comments %>
  <h3>Comments</h3>
 
  <% for comment in @comments do %>
    <p><strong><%=h(comment.author) %></strong>: </p> 
    <%= simple_format comment.text %>
  <% end %>
 
<% end %>

<h3>Post Your Comment</h3>
<%= form_for([@book, Comment.new]) do |form| %>
  <p><%= form.label :author %></p>
  <p><%= form.text_field :author %></p>
 
  <p><%= form.label :text, 'Comment' %></p>
  <p><%= form.text_area :text %></p>
 
  <%= form.submit 'Save' %>
<% end %>

<p>
  Admin Actions: 
  <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Delete', book_path(@book), :method => :delete, :confirm => "Are you sure?" %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
    <div id="user_nav">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log out", log_out_path %>
      <% else %>
        <%= link_to "Sign up", sign_up_path %> or
        <%= link_to "log in", log_in_path %>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>